Sprint 13 PR
undpun/java-shareit pull request #1
Opened 2023-05-16 05:22 UTC by undpun

2023-05-16 18:45 UTC, ohelly requested changes
Привет! В целом отличная работа, все работает корректно. Есть одно небольшое замечание - отстуствует ДТО для модели юзер и соответсвенно маппер. Также рекомендую раскидать классы по соответсвующим пакетам.

2023-05-16 18:45 UTC, ohelly commented on src/main/java/ru/practicum/shareit/mapper/Mapper.java
> +public class Mapper {
Рекомендация: Будет лучше создать маппер в каждом отдельном подпакете(item, user, etc), так как он нужен для каждого из классов.
Тут же напишу замечание, которое необходимо исправить: Отсутствует UserDto и его маппер для юзера, его необходимо добавить.

2023-05-16 18:45 UTC, ohelly commented on src/main/java/ru/practicum/shareit/user/User.java
>  public class User {
Рекомендация: Будет лучше создать отдельные подпакеты - для сервисов, для хранилищ, контроллеров, моделей, мапперов и дто.

2023-05-16 19:25 UTC, undpun commented on src/main/java/ru/practicum/shareit/mapper/Mapper.java
> +public class Mapper {
Рекомендация принята: UserController теперь принимает UserDto но также возвращает User т.к. в тестах постман должны быть id у респонса

2023-05-17 18:07 UTC, ohelly commented on src/main/java/ru/practicum/shareit/mapper/Mapper.java
> +public class Mapper {
в UserDto также можно добавить идентификатор, это нормальная практика.

2023-05-17 19:39 UTC, merged