Sprint 14 PR
undpun/java-shareit pull request #2
Opened 2023-06-09 19:06 UTC by undpun

2023-06-10 18:03 UTC, ohelly requested changes
Привет! Отличная работа, в целом работает все корректно. Есть одно небольшое замечание, которое необходимо поправить. Также оставил ряд рекомендаций, на которые стоит обратить внимание.
В случае возникновения вопросов можно смело обращаться ко мне в пачке

2023-06-10 18:03 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        for (Booking current : bookingRepository.findAllByItemIdAndStatus(itemDto.getId(), BookingStatus.APPROVED)) {
Рекомендация: Данное действие можно заменить одним запросом в БД, вместо того чтобы проходить циклом по всем. Достаточно сделать запрос поиска по итем айди, статусу и текущему времени, добавить сортировку DESC/ASC в зависимости от того, какой букинг ставим(следующий или предыдущий) и достать первый эелемент с помощью LIMIT 1

2023-06-11 09:28 UTC, undpun commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        for (Booking current : bookingRepository.findAllByItemIdAndStatus(itemDto.getId(), BookingStatus.APPROVED)) {
теперь вместо одного запроса (на все букинги айтема) два (один на след букинг и второй на последний). не догадался как сделать через один запрос. 

JPQL не поддерживает LIMIT. поэтому сделал через пагинацию как понял

2023-06-11 17:06 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Работу принимаю, можно двигаться дальше!

2023-06-12 09:43 UTC, merged